### PR TITLE
Add in place integration

### PR DESCRIPTION
**Pull request by mzaffalon**
Addresses issue #30.

### CODE REVIEW

**Comment by mzaffalon** [comment]
@stevengj Please let me know if this is what you had in mind and how this PR can be improved.

**Comment by DNF2** [comment]
This would be extremely useful for me. Any chance it could be merged?

**Comment by DNF2** [comment]
What happened, @mzaffalon? Is this gone now? Bummer...

**Comment by mzaffalon** [comment]
Oops! I have accidentally deleted my repository with the PR, sorry!
@DNF2 do you happen to have a clone of the repo?

**Comment by giordano** [comment]
https://github.com/JuliaMath/HCubature.jl/pull/64/commits/28f4d7a0be26e444459a2619f7bd9235d6a9d46b

**Comment by mzaffalon** [comment]
Will it be merged?

**Pull request closed without merging**
